name: MultiWare
version: '1.0'
main: nl.multitime.multiWare.MultiWare
api-version: '1.19'
authors: [ MultiDevelopment ]
description: Mineware from Cubecraft custom made!

commands:
  mw:
    description: MultiWare management command
    usage: /<command> <create|edit|remove|disable|enable>
